spring:
  application:
    name: poc-rsocket
  rsocket:
    server:
      port: 7000
      transport: tcp

management:
  endpoints:
    web:
      exposure:
        includ: "*"

logging.level.io.rsocket.FrameLogger: DEBUG