spring:
  application:
    name: poc-rsocket
  rsocket:
    server:
      port: 7000
#      transport: tcp
      transport: websocket

management:
  endpoints:
    web:
      exposure:
        includ: "*"