apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: poc-rsocket-image
    newName: docker.io/library/application
    newTag: 0.0.1-SNAPSHOT

resources:
  - poc-rsocket.yaml
  - nginx.yaml