apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: poc-rsocket-ingress
  namespace: ingress-nginx
  annotations:
#    value must be grater than keepAlive defined in rsocket client
    nginx.ingress.kubernetes.io/proxy-read-timeout: "80"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "80"
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: poc-rsocket
              servicePort: 7000

