apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: minimal-ingress
  namespace: ingress-nginx
  annotations:
    nginx.org/websocket-services: "poc-rsocket"
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: poc-rsocket
              servicePort: 7000

